---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: janus-idp
  namespace: argocd-backstage
spec:
  project: default
  source:
    chart: janus-idp/backstage
    repoURL: https://janus-idp.github.io/helm-backstage
    targetRevision: 2.6.0
    helm:
      releaseName: backstage
      values: 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: benbackstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
